### ISSUE TITLE
SiriusCon Live 2020

### ISSUE THREAD

**Issue by MarieJouault** [EclipseFdn/events.eclipse.org#10]
## Event Information

Event Name: SiriusCon Live 2020
Type of event: ve
Date: 18th June
Registration URL: https://bit.ly/Register_SiriusCon2020
Website URL: https://www.siriuscon.org/
Location name:
Street: 
Zip/Postal code:
City:
Country: 
Latitude:
Longitude:

### Type of event
It can be any of the following:

* dc - Demo Camp & Stammtisch
* wg - Working Group Events
* ec - EclipseCon
* ed - Eclipse Day & Hackathons
* et - Training Series
* ee - Other interesting Events
* ve - Virtual Events

**Comment by chrisguindon** [comment]
@MarieJouault Thanks for creating this request!

We need to update our instructions since we created a new platform to make it easier for everyone to submit an event.

Would you mind submitting your event here: https://newsroom.eclipse.org/node/add/events

**Comment by chrisguindon** [comment]
I created an issue to update our instructions: https://github.com/EclipseFdn/events.eclipse.org/issues/14

**Comment by chrisguindon** [comment]
SiriusCon 2020 is now listed on events.eclipse.org! 

Merci!
