### ISSUE TITLE
Missing Learn more button

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/events.eclipse.org#100]
The Eclipse Newsroom Event Form asks for an info and register link and we would like to support both via the events.eclipse.org homepage.

This is a sample event from our API:
https://newsroom.eclipse.org/api/events?parameters[upcoming_only]=1

```
	{
			"id": "37795",
			"type": "ve",
			"title": "JakartaOne Livestream",
			"date": "2020-12-08T16:00:00Z",
			"end-date": "2020-12-09T04:00:00Z",
			"locationName": "",
			"description": "JakartaOne Livestream is a one-day virtual conference for developers and technical business leaders that brings insights into the current state and future of Jakarta® EE and related technologies focused on developing cloud native Java applications.",
			"infoLink": "https://jakartaone.org/2020/",
			"registration": "https://www.crowdcast.io/e/jakartaonelivestream_dec8/register",
			"address": {
				"street": "",
				"zip": "",
				"city": "",
				"country": "Canada",
				"geoLoc": {
					"lat": "",
					"lon": ""
				}
			},
			"publish_to": [
				"eclipse_org",
				"jakarta_ee"
			]
		},
```

- Add  "Learn More" link if `infoLink` is not empty
- Add  "Register" link if `registration` is not empty

**Comment by chrisguindon** [comment]
These links should open in a new window since they are external links. This is based off feedback from @brianking

**Comment by brianking** [comment]
> These links should open in a new window since they are external links. This is based off feedback from @brianking

I'm not sure if they "should", I will defer to UX experts. I guess the question to ask is if the events page goes away, will people come back? And do we want them to?
