### ISSUE TITLE
Eclipse Foundation Events Legend

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/events.eclipse.org#105]
The original mockup had a legend for tracking:

- Eclipse Foundation Events
- Events we are attending
- Other community events of interest

![94055084-76587e00-fdaa-11ea-8dc7-1a0d3c77cd7f](https://user-images.githubusercontent.com/893942/94144926-c46b9100-fe3f-11ea-9ab3-597580275c68.png)

This was not implemented in phase 1 because we are simply not tracking that information in our API. The goal of this issue is to discuss adding a new Event field in the Eclipse Newsroom in order to track that information.

In order to properly implement this, we will need to update all our events to make sure that information exists for all of them. This is important since we will be allowing users to view past events on the events.eclipse.org website.

@jph152 @karenmcnaughton My team will commit to implementing this feature if your team can commit to updating all our events. The alternative would be to set a default value when that field is not set for an event but I think this could cause more confusion to our users.

Is this something we want to do or should we keep the legend as-is? Right now, the legend is for the Event type.

![Screen Shot 2020-09-24 at 8 35 05 AM](https://user-images.githubusercontent.com/893942/94145636-dd287680-fe40-11ea-8cdd-7a12dd2812ef.png)

**Comment by jph152** [comment]
That would do a smart way to organize the page. I can spend some time updating the events tomorrow

**Comment by chrisguindon** [comment]
> That would do a smart way to organize the page. I can spend some time updating the events tomorrow

I think we are close to 380 events. This is probably a full day of work for you if we decide to do this work...

**Comment by jph152** [comment]
Ah I figured it was just the events currently displayed on the page. Definitely best to wait on this then

**Comment by chrisguindon** [comment]
We could start with current events. We will add the new field to track this info from the newsroom website.

We can discuss how we want to deal with past events via issue #6

**Comment by chrisguindon** [comment]
I am preparing a patch that will do the following:

- Add a new Attendance Type field.
- This new field will have 3 option: 
  - ef_event|Eclipse Foundation Events
  - ef_attending|Events we are attending
  - other|Other community events of interest
- This field will ONLY be editable by moderators. This is similar to the geocoordinate field. 
- If this field is not set for an event, our API will say that the event attendance type is set to "other". @jph152 This means that won't need to update all our events but only those that have a type of  ef_event & ef_attending.

Please start by updating our current events as we can roll this out sooner rather than later. We will then wait that you are done updating past events before we complete #6.

I will post an update here one the new field is live on production.

**Comment by chrisguindon** [comment]
The change is now on production! @jph152 you can start updating events whenever you can now! Please keep us updated on the status via this issue!

**Comment by jph152** [comment]
Will do! Thanks Chris

**Comment by chrisguindon** [comment]
@flora8984461 has implemented the legend on our preview server:
https://deploy-preview-110--eclipsefdn-events.netlify.app/

Let us know what you guys think!

**Comment by jph152** [comment]
All current events are updated with the new field https://deploy-preview-110--eclipsefdn-events.netlify.app/
