### ISSUE TITLE
Archives to static HTML previous EclipseCon sites

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/events.eclipse.org#120]
Checklist of sites we need to archive:

- [x] 2004   https://events.eclipse.org/2004/eclipsecon/  
- [x] 2005   https://events.eclipse.org/2005/eclipsecon/  
- [x] 2006   https://events.eclipse.org/2006/eclipsecon/        
- [x] 2007     https://events.eclipse.org/2007/eclipsecon/
- [x] 2008   https://events.eclipse.org/2008/eclipsecon/  
- [x] 2009      https://events.eclipse.org/2008/eclipsecon/    
- [x] 2010     https://events.eclipse.org/2010/eclipsecon/
- [x] 2011    https://events.eclipse.org/2011/eclipsecon/
- [x] 2012          https://events.eclipse.org/2012/eclipsecon/
- [x] 2013             https://events.eclipse.org/2013/eclipsecon/
- [x] locationcon     https://events.eclipse.org/2017/locationcon/
- [x] europe2011       https://events.eclipse.org/2011/europe/
- [x] europe2012 https://events.eclipse.org/2012/europe/
- [x] europe2013  https://events.eclipse.org/2013/europe/
- [x] europe2014   https://events.eclipse.org/2014/europe/
- [x] europe2015 https://events.eclipse.org/2015/europe/
- [x] europe2016    https://events.eclipse.org/2016/europe/
- [x] europe2017 https://events.eclipse.org/2017/europe/
- [x] france2013       https://events.eclipse.org/2013/france/
- [x] france2014    https://events.eclipse.org/2014/france/
- [x] france2015    https://events.eclipse.org/2015/france/  
- [x] france2016 https://events.eclipse.org/2016/france/
- [ ] france2017 https://events.eclipse.org/2017/france/
- [ ] france2018       https://events.eclipse.org/2018/france/
- [x] na2014    https://events.eclipse.org/2014/na/
- [x] na2015   https://events.eclipse.org/2015/na/
- [x] na2016         https://events.eclipse.org/2016/na/
- [x] na2017    https://events.eclipse.org/2017/na/
- [x] summiteurope2006      https://events.eclipse.org/2006/summiteurope/
- [x] summiteurope2007  https://events.eclipse.org/2007/summiteurope/
- [x] summiteurope2008 https://events.eclipse.org/2008/summiteurope/
- [x] summiteurope2009 https://events.eclipse.org/2009/summiteurope/
- [x] summiteurope2010 https://events.eclipse.org/2010/summiteurope/

**Comment by ericpoirier** [comment]
Here is a list of things we will need to do in order to complete the arcvhing of the websites listed above.

- [ ] Create aliases for each EclipseCon websites that have been archived to point to their respective folder in events.eclipse.org (Matt)
- [ ] Remove database tables for archived websites (Matt)
- [ ] Remove Drupal themes from Solstice theme (Eric)
- [ ] Clean up Drupal site folder containing settings.php (Eric)
- [ ] Clean up make files (Eric)
- [ ] Clean up webdev-cron (Eric)

**Comment by flora8984461** [comment]
I don't have access to tick the checkbox, creating a list for myself that I have created patches:
- [ ]  2010
- [ ]  2011
- [ ]  2012
- [ ]  2013
- [ ]  locationcon
- [ ]  europe2011
- [ ]  europe2012
- [ ]  europe2013
- [ ]  europe2014
- [ ]  europe2015
- [ ]  europe2016
- [ ]  europe2017
- [ ]  foss4g2015
- [ ]  foss4g2016
- [ ]  foss4g2018
- [ ]  france2013
- [ ]  france2014
- [ ]  france2016
- [ ]  france2017
- [ ]  france2018
- [ ]  na2014
- [ ]  na2015
- [ ]  na2016
- [ ]  na2017
- [ ]  converge2017
- [ ]  summiteurope2006
- [ ]  summiteurope2007
- [ ]  summiteurope2008
- [ ]  summiteurope2009
- [ ]  summiteurope2010

**Comment by ericpoirier** [comment]
> I don't have access to tick the checkbox, creating a list for myself that I have created patches:

Ok, it will be important to remember to update the master list once the site that you have worked on have been merged.

**Comment by ericpoirier** [comment]
While updating the list of remaining websites to be added, I noticed the following things:

europe2015
Not the correct background image

europe2017
We are missing a Sponsor logo

**Comment by flora8984461** [comment]
> While updating the list of remaining websites to be added, I noticed the following things:
> 
> europe2015
> Not the correct background image
> 
> europe2017
> We are missing a Sponsor logo

I think these are fixed with my new PR #153

**Comment by flora8984461** [comment]
We are missing images for 
 summiteurope2007
 summiteurope2008
 summiteurope2009
 summiteurope2010

https://eclipsefdn-eclipsecon-archive.netlify.app/summiteurope2007/
https://eclipsefdn-eclipsecon-archive.netlify.app/summiteurope2008/
https://eclipsefdn-eclipsecon-archive.netlify.app/summiteurope2009/
https://eclipsefdn-eclipsecon-archive.netlify.app/summiteurope2010/

**Comment by chrisguindon** [comment]
I plan on removing https://eclipsefdn-eclipsecon-archive.netlify.app  once you are done with this task!

**Comment by ericpoirier** [comment]
@flora8984461 I noticed that for France2017 and France2018 the social media links in the footer are not aligned properly. Can you have a look at that?

Thanks

https://events.eclipse.org/2017/france/
https://events.eclipse.org/2018/france/
