### ISSUE TITLE
Double links on papers

### ISSUE THREAD

**Issue by phkrief** [EclipseFdn/events.eclipse.org#131]
**Describe the bug**
I wanted to complete the SAM-IoT agenda by adding the links to accepted papers. Knowing we don't have a specific slot (such as vod: or slides:) for papers, I added directly the link in the description, just below the authors. For example:

--

>     - name: 'Risk Assessment in IoT Case Study: Collaborative Robots System'
>       presenter: <a href="speakers/#salim-chehida">Salim Chehida</a>
>       type: session
>       time: 13:45 - 14:05
>       abstract: |
>              <p><strong>Authors:</strong>
>              <ul>
>                   <li>Salim Chehida, Université Grenoble Alpes</li>
>                   <li>Abdelhakim Baouya, Université Grenoble Alpes</li>
>                   <li>Miquel Cantero, Robotnik Automation S.L.L</li>
>                   <li>Paul-Emmanuel Brun, Airbus Defence & Space</li>
>                   <li>Guillemette Massot, Airbus Defence & Space</li>
>              </ul>
>              <strong>Paper:</strong> <a target="_blank" href="http://ceur-ws.org/Vol-2739/paper_1.pdf">CEUR link</a>
>              
>              <strong>Abstract:</strong> Security is one of the crucial challenges in the design and development of IoT applications. 
>              This paper presents an approach that focuses on existing security standards to evaluate and 
>              analyse the potential risks faced by IoT systems. It begins by identifying system assets and 
>              their associated vulnerabilities and threats. A list of security objectives and technical 
>              requirements are then defined to mitigate the risks and build a secure and safe system. 
>              We use our approach to assess risks in the robotic system for supporting the movement of loads 
>              in a warehouse.</p>
>       vod: https://youtu.be/SOJCH-alwjU
>       slides: https://www.slideshare.net/BrainIoT/samiot-risk-assessment-in-iot-case-study-collaborative-robots-system

--
Unfortunately, the result is not what I expected: 
- First I get 2 icons representing 2 links on the agenda following the title of the paper
![image](https://user-images.githubusercontent.com/6196602/99181270-afb7c500-272d-11eb-87b7-bdd4506616a8.png)

- None of these links work

**To Reproduce**
https://deploy-preview-130--eclipsefdn-events.netlify.app/2020/sam-iot/

Thanks a lot for your help

**Comment by autumnfound** [comment]
This is caused by adding the link to the body. This is due to how we store the information for the modal information, which has a side effect of not accepting any sort of anchor tags. We can look at tweaking this to allow links, but it will take a couple of days

**Comment by phkrief** [comment]
Thx @autumnfound, it was my guess :-).
Would it help if we could add a new column on the agenda with the link to the paper instead of fixing this issue?

**Comment by autumnfound** [comment]
I don't think adding a paper column would be the right solution here. Adding papers seems like it would be a rare case rather than the usual case like slides and vods, and this can be solved with your current solution easily

**Comment by phkrief** [comment]
Fine with me then

**Comment by flora8984461** [comment]
This should be fixed by https://github.com/EclipseFdn/hugo-solstice-theme/commit/16db80887a6e8837acd45b7e91ae8a0c1bc1806c, I'll check if the events site's theme has been updated to 0.0.106

**Comment by flora8984461** [comment]
Hello @phkrief 
I made a patch to update the theme version and your issue is fixed here https://github.com/EclipseFdn/events.eclipse.org/pull/160
