### ISSUE TITLE
Refresh the events.eclipse.org homepage

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/events.eclipse.org#15]
We are thinking of re-designing the events.eclipse.org homepage.

The focus right now is on the map and we would like to change that and prioritize event information.

I am creating this bug to allow us to brainstorm ideas.

**Comment by shanda-eclipse** [comment]
Wish list:
- Card style listings (ex https://www.redhat.com/en/events or https://events.linuxfoundation.org/)
- Ability to filter events by location (continent or virtual) and subject matter (working group)
- Visually interesting, but we do not want to have to upload images for every event

Display the following info for each event:
- Event name
- Event date and time (1-day events should show start and end time, multiday events should show start and end dates)
- Short description
- Up to 2 buttons/event: visit event website and register

**Comment by chrisguindon** [comment]
As discussed on https://github.com/EclipseFdn/openadx.eclipse.org/pull/87,

It should be possible to view past events from each working group.

**Comment by shanda-eclipse** [comment]
Resources from Matt: 

I updated this XD link to a Development link with downloadable assets: https://xd.adobe.com/view/dbc61752-c869-4bab-525b-de389b574b56-adf7/ 

I am also including a local XD file if needed here: https://drive.google.com/drive/folders/1G6mQzGAJEMuW-Liiu4Z8DifU0IKGCjWM?usp=sharing

**Comment by flora8984461** [comment]
Rough todo issue:

- [ ] 1) build up the layout skeleton and list out the events
- [ ] 2) search bar on the top left
- [ ] 3) load more events (lazy loading)
- [ ] 4) filters on the left under search bar (by working groups, dates...)
- [ ] 5) read more on each event

**Comment by annejacko** [comment]
Adding feedback on the new page as viewed here: https://deploy-preview-87--eclipsefdn-events.netlify.app/

Looks good.. the one thing that I miss is a list of all upcoming events by date. I realize the squares featuring the various events are ordered by date, but that's not obvious. If someone wanted to know "what coming up next week" they would have to look a bit. Maybe a list by date on the left side?

**Comment by chrisguindon** [comment]
@flora8984461 I just spoke with Thabang and we have some feedback:

- Add the jumbotron (Header)
- Change the filter caption from "Working Group" to  "Categories"
- Change eclipse.org to other in the "Categories" filter.
- Add a "Categorie" option for Eclipse IDE. I will be adding the option shortly: 
  - eclipse_ide|<a href="https://www.eclipse.org/eclipseide" target="_blank">Eclipse IDE</a>

**Comment by flora8984461** [comment]
For other types, bg images

**Comment by flora8984461** [comment]
Currently, we have event types:

- EclipseCon
- Virtual Event
- Demo Camps & Stammtisch
- Working Group Events
- Training Series
- Other interesting Events
- Unknown

But from the XD design (https://xd.adobe.com/view/dbc61752-c869-4bab-525b-de389b574b56-adf7/), I only have three background images for event card.

According to @chrisguindon , we want to use different background images for each type of events. 

For now, I temporarily replace other types of events using default black background.

Would you mind providing me for each event type, what background image would you like to use? 

The screenshot shows how I organize the images with event types so far.

![image](https://user-images.githubusercontent.com/39588094/93912652-024aa700-fcd2-11ea-8cad-79b162ab0f54.png)

**Comment by chrisguindon** [comment]
@karenmcnaughton can your team provide the missing images?

**Comment by flora8984461** [comment]
> @flora8984461 I just spoke with Thabang and we have some feedback:
> 
> * Add the jumbotron (Header)
> * Change the filter caption from "Working Group" to  "Categories"
> * Change eclipse.org to other in the "Categories" filter.
> * Add a "Categorie" option for Eclipse IDE. I will be adding the option shortly:
>   
>   * eclipse_ide|[Eclipse IDE](https://www.eclipse.org/eclipseide)

I updated these feedbacks, just for the subtitle is the text I copied from XD mockups. Please let me know the text you want to change to or hide them temporarily. 

Preview: https://deploy-preview-87--eclipsefdn-events.netlify.app/

**Comment by chrisguindon** [comment]
@karenmcnaughton,

Thabang asked us to make sure that we included the jumbotron for the events.eclipse.org re-design:
https://deploy-preview-87--eclipsefdn-events.netlify.app/

Is it possible for your team to provide content to replace the lorem ipisum text?

**Comment by chrisguindon** [comment]
> I updated these feedbacks, just for the subtitle is the text I copied from XD mockups. Please let me know the text you want to change to or hide them temporarily.

Let's keep it for now! I've sent an email to Thabang and @karenmcnaughton about the missing text and missing images.

**Comment by karenmcnaughton** [comment]
Text for the lorem ipsum in the Jumbotron: "Join the world’s leading technologists and open source leaders at Eclipse Foundation events to share ideas, learn and collaborate."

**Comment by flora8984461** [comment]
> Text for the lorem ipsum in the Jumbotron: "Join the world’s leading technologists and open source leaders at Eclipse Foundation events to share ideas, learn and collaborate."

Updated.

**Comment by jph152** [comment]
Do we need certain specs for these background images? Does 380 x 340px work?

**Comment by flora8984461** [comment]
> Do we need certain specs for these background images? Does 380 x 340px work?

@chrisguindon  From my code, I already fix the size of each event card, so even the img is bigger, won't cause the card bigger, 380 x 340px works. But we should keep the file size small so that it is light when loading. What do you think?

**Comment by chrisguindon** [comment]
@flora8984461 I would stay consistent with what we currently have:
https://deploy-preview-87--eclipsefdn-events.netlify.app/images/WorkingGroupEvents.png?ad9312c2776f2636581cd08dd7a1b5a6

This image is 369 x 320px

**Comment by flora8984461** [comment]
> @flora8984461 I would stay consistent with what we currently have:
> https://deploy-preview-87--eclipsefdn-events.netlify.app/images/WorkingGroupEvents.png?ad9312c2776f2636581cd08dd7a1b5a6
> 
> This image is 369 x 320px

@jph152   After discussion with Chris, probably let's keep it consistent as 369 x 320px, thanks

**Comment by chrisguindon** [comment]
> Adding feedback on the new page as viewed here: https://deploy-preview-87--eclipsefdn-events.netlify.app/
> 
> Looks good.. the one thing that I miss is a list of all upcoming events by date. I realize the squares featuring the various events are ordered by date, but that's not obvious. If someone wanted to know "what coming up next week" they would have to look a bit. Maybe a list by date on the left side?

@annejacko,

Thanks for the feedback! I decided to create a separate issue for your request:
https://github.com/EclipseFdn/events.eclipse.org/issues/95

I think we need more time to discuss before we roll this feature out!

**Comment by chrisguindon** [comment]
@jph152 @flora8984461 I created https://github.com/EclipseFdn/events.eclipse.org/issues/96 to track the background image effort since I am planning to push @flora8984461 work on production this afternoon and will be closing this bug.

**Comment by jph152** [comment]
@flora8984461 Can we make the jumbotron text lowercase? 
"Join the world’s leading technologists and open source leaders at Eclipse Foundation events to share ideas, learn and collaborate."

**Comment by flora8984461** [comment]
> @flora8984461 Can we make the jumbotron text lowercase?
> 
> > Join the world’s leading technologists and open source leaders at Eclipse Foundation events to share ideas, learn and collaborate.

Yes, updated.

**Comment by chrisguindon** [comment]
The changes have been merged to the Master branch! We should see a new version of events.eclipse.org shortly!

Thank you to everyone involved @flora8984461 @jph152 @annejacko @shanda-eclipse @autumnfound @ericpoirier.
