### ISSUE TITLE
 Error running command: Command did not finish within the time limit

### ISSUE THREAD

**Issue by phkrief** [EclipseFdn/events.eclipse.org#158]
**Describe the bug**
I try to update the SAM IoT webpage but the build is interrupted with this error...

Can you fix that?

Thx a lot

**Comment by autumnfound** [comment]
Hi Philippe, this is caused by your branch being out of date. We had extra resources that were timing out builds and using a lot of our build minutes for our preview site which have been changed to be static and not cause this problem. Please rebase your changes and you should be good to go!

**Comment by phkrief** [comment]
Oops! Sorry about that. I was convinced that I synched my workspace.
It is fixed now.

Thx a lot

Kind regards
*—*
Philippe Krief, PhD
Research Relations Director | Eclipse Foundation, Inc.
Eclipse Foundation <http://www.eclipse.org/>: The Platform for Open
Innovation and Collaboration
M: +33 (0)6 21 01 06 81

Annastr. 46, D-64673 Zwingenberg
Handelsregister: Darmstadt HRB 92821
Managing Directors: Gaël Blondelle, Mike Milinkovich
