### ISSUE TITLE
Launch Jakarta EE 9 page

### ISSUE THREAD

**Issue by karenmcnaughton** [EclipseFdn/events.eclipse.org#161]
The go live for the Jakarta EE 9 page is late in the day on December 7th please.
Can you remove the text: "Jakarta EE 9 is coming on December 8" before go live.
Thank you!

**Comment by chrisguindon** [comment]
This is the wrong repo @karenmcnaughton

**Comment by chrisguindon** [comment]
I created one under jakarta.ee: https://github.com/jakartaee/jakarta.ee/issues/1022
