### ISSUE TITLE
Event Website: SAM IoT 2020

### ISSUE THREAD

**Issue by ericpoirier** [EclipseFdn/events.eclipse.org#17]
Create a new website for SAM IoT.

Here is a link for the initial bug:
https://foundation.eclipse.org/infrazilla/show_bug.cgi?id=3708

I'm creating this issue because this is where we have decided to host the website and we would like to port the discussion of that new website over to this issue.

**Comment by shanda-eclipse** [comment]
Final content for the page: Save the date

Eclipse SAM IoT 2020
Security, Artificial Intelligence and Modelling for the next generation Internet of Things
Virtual Conference | September 16-17, 2020

Mark your calendars for Eclipse SAM IoT 2020, Sept 16-17. 

The Eclipse SAM IoT conference will bring together industry experts and researchers working on the next generation IoT, especially focussing on security and privacy, Artificial Intelligence, and modelling. 

The call for papers is open. Download the call for papers now and talk with your colleagues about participating at Eclipse SAM IoT 2020.

(sorry, I can't see the staging site to track changes to the content)

**Comment by ericpoirier** [comment]
Hi Shanda,

Here is the url for staging:
https://deploy-preview-11--eclipsefdn-events.netlify.app/2020/sam-iot/

Also note that once this is on production, it will keep the same url structure. Which would be:
events.eclipse.org/2020/sam-iot/

**Comment by chrisguindon** [comment]
I posted a comment on the PR but I should have posted my question here:
https://github.com/EclipseFdn/events.eclipse.org/pull/11

@shanda-eclipse are you the owner of this event?

Who should we expect to give us a +1 for making this page live?

**Comment by phkrief** [comment]
@ericpoirier we have been asked by @PaulW to move the dates by one day. SO now, the event is programmed from the 17-18 September.
Thx for fixing that in the title and in the text:

Virtual Conference | September 17-18, 2020

Mark your calendars for Eclipse SAM IoT 2020, Sept 17-18.

Thx a lot

**Comment by phkrief** [comment]
I also attach the current version of the CFP to attach to the "Call for Papers" button.
Thx a lot
[Flyer-SAM IoT 2020-1.3.pdf](https://github.com/EclipseFdn/events.eclipse.org/files/4618350/Flyer-SAM.IoT.2020-1.3.pdf)

**Comment by ericpoirier** [comment]
I updated staging with the last updates.

https://deploy-preview-11--eclipsefdn-events.netlify.app/2020/sam-iot/

Let me know if there's anything else.

I'll wait for your +1 to merge this to production.

Thanks.

**Comment by gaelblondelle** [comment]
+1

**Comment by ChristieWittEclipse** [comment]
We had a request to make the line orange (#f7941e) below the title in the Jumbotron (see line in screenshot). I know we had discussed keeping the template generic and simple, so please advise if this change is too much.

![Screen Shot 2020-05-19 at 12 50 16 PM](https://user-images.githubusercontent.com/58480647/82354943-8365fa80-99cf-11ea-9f9e-45d12817c571.png)

**Comment by chrisguindon** [comment]
@ChristieWittEclipse If we make the change, it will be orange for all event websites under events.eclipse.org!

If you still think we should do it, feel free to create a new request asking us to make this change!

**Comment by ChristieWittEclipse** [comment]
Okay I will follow up with SAM IoT event organizers, I don't think this is mandatory for all websites that use this template.

**Comment by phkrief** [comment]
This Issue is tagged as closed. Are we supposed to continue to exchange on this one?
Thx for your help

**Comment by chrisguindon** [comment]
@phkrief The event website was launched. I expect a new issue for new changes!

**Comment by phkrief** [comment]
Great! Thx @chrisguindon. It was my understanding too ;-)
