### ISSUE TITLE
Eclipse SAAM Mobility 2021

### ISSUE THREAD

**Issue by sjkiwai** [EclipseFdn/events.eclipse.org#170]
Hi there,
We'd like to request setup for the SAAM Mobility website. The website template is here https://docs.google.com/document/d/11dzhZ--1cio7Ci3X8L-D598jo7J-GFeWbqgXiAw60IQ/edit#. Happy to review the document with you.

Regards,
Susan

**Comment by sjkiwai** [comment]
The paper submissions portal needs a webpage for reference. Will the url be:  events.eclipse.org/2021/saam-mobility  ? Thank you!

**Comment by autumnfound** [comment]
Current preview is available here: https://deploy-preview-171--eclipsefdn-events.netlify.app/2021/saam-mobility

There doesn't seem to be a lot of information in the document just yet, just the first section and the basic event information? Otherwise it looks like the sample content was left in

**Comment by autumnfound** [comment]
I've updated the site with some sample content as requested in the event document. We can remove or comment that before this goes live if we don't have that content.

**Comment by chrisguindon** [comment]
Closing the issue now that the website is live!

Let's re-open new issues if we have more changes to do!
