### ISSUE TITLE
Eclipse SAAM Mobility 2021 Banner

### ISSUE THREAD

**Issue by phkrief** [EclipseFdn/events.eclipse.org#175]
Could you have the kindness to replace the default banner of the SAAM Mobility event with the attached file?
Thx a lot
![banniere-eclipse-sans-texte](https://user-images.githubusercontent.com/6196602/108726325-93df6e80-7527-11eb-8fa9-e59976485da2.jpg)

**Comment by phkrief** [comment]
For your information, here is how we organised the message on this banner, in case it helps
![banniere-eclipse-2](https://user-images.githubusercontent.com/6196602/108726469-c12c1c80-7527-11eb-9e72-75c4ac931a69.jpg)

**Comment by flora8984461** [comment]
Hi @phkrief @chrisguindon 
Please check the preview: https://deploy-preview-176--eclipsefdn-events.netlify.app/2021/saam-mobility/

I wonder do I need to change the background image also for "Technical topics of interest" Section and "Technical Program Committee" section? Or just the header?

Thanks!

**Comment by chrisguindon** [comment]
@phkrief Do you have a preference?

**Comment by phkrief** [comment]
Thanks @flora8984461 for this try.
I made a header darker and created a dark background for the other sections. Would you mind trying that?
![header](https://user-images.githubusercontent.com/6196602/108772419-45e55d80-755d-11eb-805f-b3de5b2592ab.jpg)
![middle-page](https://user-images.githubusercontent.com/6196602/108772430-4847b780-755d-11eb-9bb4-2b5685799637.jpg)

WDYT? Thx

**Comment by phkrief** [comment]
I realized that the second one doesn't match well with the first one so I have another suggestion
![middle-page-2](https://user-images.githubusercontent.com/6196602/108773362-84c7e300-755e-11eb-9be0-27b81b875c10.jpg)
WDYT?

**Comment by flora8984461** [comment]
Hi @phkrief , Thanks for the new banners and reminder, And I am so sorry for the late reply! 

Please have a check on the preview with the latest image you shared: 
https://deploy-preview-176--eclipsefdn-events.netlify.app/2021/saam-mobility/

-----------------------------------------------------------------------------------------------------

And I also tried with the previous image you shared, which I only took a screenshot:

![image](https://user-images.githubusercontent.com/39588094/109012902-88ec2180-7680-11eb-94fc-6aa41c805c4f.png)


Which one do you prefer?


And another question is, do you want to also replace the other two sections' background as the new image? 
For "Technical topics of interest" Section and "Technical Program Committee" section.


Thank you so much for your patience!

**Comment by autumnfound** [comment]
As a third party, the latest image provided is really snappy! The dark colors pop much better, with the whole head section passing accessibility for its current content. The previous image with the light ribbon under the text makes it a little hard to read as there is a lot going on in that section, though it still passes accessibility.

**Comment by phkrief** [comment]
Thanks @autumnfound for sharing your thoughts.  Greatly appreciated

**Comment by phkrief** [comment]
> And another question is, do you want to also replace the other two sections' background as the new image?
> For "Technical topics of interest" Section and "Technical Program Committee" section.
Yes, please, we have to stay with this one now, I guess.
I saw your changes, Will I be able to play with these bitmaps later on, if we decide to adapt them?
Thanks

**Comment by flora8984461** [comment]
Hi @phkrief For sure, once this is merged to master, you can update the images in https://github.com/flora8984461/events.eclipse.org/tree/yiliu/master/saamBanner/less/images/default 

which are called `saam-mobility-2021-header.jpg` and `saam-mobility-2021-middle.png` . 

And then run `npm run production` to build with the new images. 

If there are image file names change (especially for file name extension, like from jpg to png or vice versa), you can go to https://github.com/flora8984461/events.eclipse.org/blob/yiliu/master/saamBanner/less/_variables.less#L18-L19 to change the file path. (Currently I am pointing to my own github branch, you will replace them on your own branch, but the same folders)

Please feel free to ask me if more explanations needed. Thanks!
