### ISSUE TITLE
SAAM Mobility event is missing on the main events page

### ISSUE THREAD

**Issue by phkrief** [EclipseFdn/events.eclipse.org#178]
Hi Web Team,

I was expecting to see the Eclipse SAAM Mobility event listed on the events page (https://events.eclipse.org/). But it is not the case.
Does this mean that even if we create the event under the website, we have to declare it to appear in the event list?

Thx

**Comment by chrisguindon** [comment]
@phkrief  To promote an event on any EF property, please submit the information to our Newsroom website: https://newsroom.eclipse.org/
