### ISSUE TITLE
Update content for SAMIoT 2020 Conference

### ISSUE THREAD

**Issue by Ioana240** [EclipseFdn/events.eclipse.org#19]
Hi everyone,

The EU research team and the external organization team have decided to create a version 2 of the SAMIoT conference. The initial target for the website to go live is Friday, May 22. 

This is the document with the content for the webpage version 2: https://docs.google.com/document/d/17boCj2__Vj6NMw7LiSHRL4mF9aJgtKEtFYFHAmA7yw4/edit#

Please let us know if this would be feasible until May 22 and what further information is needed.

Many thanks in advance!
Ioana

**Comment by chrisguindon** [comment]
@Ioana240,

We will do our best but for future reference, please plan to give us 5 business days to implement an event website as we might need to work with you if things are missing and we also have other priorities!

**Comment by ericpoirier** [comment]
Hi,

I'm looking at the Google document and I don't get what the revisions are. Is this something I should be looking at or should I just care about the second part of the document which is the layout.

Thanks.

**Comment by chrisguindon** [comment]
@ericpoirier It's not really clear but I think you are expected to follow the second part.

**Comment by chrisguindon** [comment]
@Ioana240 This is a really rough draft:
https://deploy-preview-20--eclipsefdn-events.netlify.app/2020/sam-iot/

Could you tell us what we should change before making this live?

**Comment by annejacko** [comment]
Hi -- site is looking good. @Ioana240 I did notice something that I would change. In the list of "Importnat Dates," the format of the dates is inconsistent. The first two abbreviate the month, and the last two do not. I would suggest NOT using abbreviations here, and spelling out "August" and "September" for the last two dates.

**Comment by phkrief** [comment]
@chrisguindon @ericpoirier thanks for this first draft.
We have some comments we would like to cover and prioritize with you this afternoon if you are available. I will send you an invitation on zoom.
================
Feedback:
- Can we move the CFP button before the description and onto the banner background
- Tagline: change style so it doesn’t look like a header
- Description: 
   - Line breaks - September should be on same line as dates
   - Justify text (rather than centred?)
- Remove Co-organized and Supported by logos
- Blocks/icons for technical topics of interest - fontawesome 
- Date correction (months in full)
- Button for combined CFP and Submission Guidelines 
    - Label: Download 
- Organizing Committees - remove colons (after General chairs)
    - PC Chair => Technical Program Committee Chair, remove colon
- Logos - add labels co-organized by and supported by 
    - Use Brain-IoT logo without the tagline
- Sign up to our newsletter banner - links to Upcoming events?

**Comment by Ioana240** [comment]
@annejacko @ericpoirier @chrisguindon Thank you everyone for making the changes.  I agree with you, Anne, we should remove the abbreviations from the "Important Dates" section.

@phkrief From what I remember from our SAMIoT update call today, Susan mentioned that the Call for Papers button that leads to the PDF with the topics of interest and submission guidelines are from version 1.3 and now we have an updated version of that PDF that we should use as PDF attached to the landing page. Please let me know if I misunderstood this and attach the document to the bug if we have a new version. Many thanks!

**Comment by Ioana240** [comment]
@ericpoirier @chrisguindon There is a version 3 of the CFP PDF document that is currently being updated. Will upload it in the bug once the document is ready. Thank you!

**Comment by phkrief** [comment]
Please replace BRAIN-IoT logo with this logo.
Thx a lot

![BRAIN-IoT_Logo_Wordmark_HD](https://user-images.githubusercontent.com/6196602/82689985-b0c6d880-9c5b-11ea-9d6b-05e18be13e63.jpg)

**Comment by phkrief** [comment]
Please use the following icons for the 3 different event topics:

- Security by Fauzan Adiima from the Noun Project (https://thenounproject.com/search/?q=security&i=3349833)
- Artificial Intelligence by priyanka from the Noun Project (https://thenounproject.com/search/?q=artificial%20intelligence&i=2858867)
- Tree by Gacem Tachfin from the Noun Project (https://thenounproject.com/search/?q=modelling&i=2710243)

![noun_Artificial Intelligence_2858867](https://user-images.githubusercontent.com/6196602/82690446-84f82280-9c5c-11ea-8ce1-1986ccf6b9f0.png)
![noun_Security_3349833](https://user-images.githubusercontent.com/6196602/82690448-86294f80-9c5c-11ea-9cdb-72c85c741c1b.png)
![noun_Tree_2710243](https://user-images.githubusercontent.com/6196602/82690452-86c1e600-9c5c-11ea-9115-dc667157330c.png)

**Comment by phkrief** [comment]
By default, they include the attribution in the file. Do you want that I crop the files?

**Comment by ericpoirier** [comment]
> Please replace BRAIN-IoT logo with this logo.
> Thx a lot
> 
> ![BRAIN-IoT_Logo_Wordmark_HD](https://user-images.githubusercontent.com/6196602/82689985-b0c6d880-9c5b-11ea-9d6b-05e18be13e63.jpg)

Hi Philippe,

Can you provide a logo with transparent background?

**Comment by phkrief** [comment]
Here we go !

![BRAIN-IoT_Logo_Wordmark_HD](https://user-images.githubusercontent.com/6196602/82701176-f1c8e800-9c6f-11ea-9a89-a2ee7d5439d5.png)

**Comment by ericpoirier** [comment]
> @chrisguindon @ericpoirier thanks for this first draft.
> We have some comments we would like to cover and prioritize with you this afternoon if you are available. I will send you an invitation on zoom.
> 
> Feedback:
> 
>     * Can we move the CFP button before the description and onto the banner background
> 
>     * Tagline: change style so it doesn’t look like a header
> 
>     * Description:
>       
>       * Line breaks - September should be on same line as dates
>       * Justify text (rather than centred?)
> 
>     * Remove Co-organized and Supported by logos
> 
>     * Blocks/icons for technical topics of interest - fontawesome
> 
>     * Date correction (months in full)
> 
>     * Button for combined CFP and Submission Guidelines
>       
>       * Label: Download
> 
>     * Organizing Committees - remove colons (after General chairs)
>       
>       * PC Chair => Technical Program Committee Chair, remove colon
> 
>     * Logos - add labels co-organized by and supported by
>       
>       * Use Brain-IoT logo without the tagline
> 
>     * Sign up to our newsletter banner - links to Upcoming events?

Hi everyone,

I made those updates and they are now on staging.

https://deploy-preview-20--eclipsefdn-events.netlify.app/2020/sam-iot/

Let me know if there's anything else before going live.

Thanks!

**Comment by ericpoirier** [comment]
Hi Philippe,

I updated the staging page to add the Call for Papers link to the header.

https://deploy-preview-20--eclipsefdn-events.netlify.app/2020/sam-iot/

**Comment by phkrief** [comment]
Thanks a lot @ericpoirier!

Please see attached to this comment the Call for Papers PDF. Please attach it to both buttons and publish the page.

[Flyer-SAM IoT 2020 + Submission Guidelines Version 3.pdf](https://github.com/EclipseFdn/events.eclipse.org/files/4678608/Flyer-SAM.IoT.2020.%2B.Submission.Guidelines.Version.3.pdf)

+1

They are late in providing the template but we should publish the page anyway... I will give you the missing template file when it will be ready.
Thanks a lot

**Comment by phkrief** [comment]
OOps, Enrico noticed an error on one name: "Prabhakaran Kasinathan" instead of "Prabhakaran Kasinatha". The "n" at the end of the first name is missing...
It must be my fault

**Comment by phkrief** [comment]
Here is the new list of Technical Program Committee if you have time t update it now. Thx a lot

- Luca Anselma, University of Turin
- Paolo Azzoni, Eurotech
- Ilaria Bosi, LINKS Foundation
- Paolo Brizzi, Competence Center Industry Manufacturing 4.0
- Benoit Combemale, University of Toulouse INRIA
- Davide Conzon, LINKS Foundation
- João Pedro Correia dos Reis, Faculty of Engineering, University of Porto - FEUP
- Maria Teresa Delgado, Eclipse Foundation
- Frederic Desbiens, Eclipse Foundation
- Marco Jahn, Eclipse Foundation
- Prabhakaran Kasinathan, Siemens AG - Cybersecurity Technologies
- Zakaria Laaroussi, Ericsson Finland
- Cesar Martin, Information Catalyst for Enterprise - ICE
- Claudio Pastrone, LINKS Foundation
- Mohammad Rifat Ahmmad Rashid, University of Liberal Arts Bangladesh – ULAB
- Alejandra Ruiz Lopez, Tecnalia
- Xu Tao, LINKS Foundation
- Massimo Vecchio, Università degli Studi eCampus

**Comment by phkrief** [comment]
I forgot to mention that we would like to mention the icon's attributions. I don't know waht would be the best place on the page for that.
Based on https://thenounproject.zendesk.com/hc/en-us/articles/200509928-How-do-I-give-creators-credit-in-my-work- you could:

- either mention attributions w/o links

“Security” icon by Fauzan Adiima, from thenounproject.com.
"Artificial Intelligence" by priyanka, from thenounproject.com.
"Tree" by Gacem Tachfin, from thenounproject.com.

- or w/links

“[Security](https://thenounproject.com/search/?q=security&i=3349833)” icon by Fauzan Adiima, from [the Noun Project](http://thenounproject.com/).
"[Artificial Intelligence](https://thenounproject.com/search/?q=artificial%20intelligence&i=2858867)" by priyanka, from [the Noun Project](http://thenounproject.com/).
"[Tree](https://thenounproject.com/search/?q=modelling&i=2710243)" by Gacem Tachfin, from [the Noun Project](http://thenounproject.com/).

Thanks a lot

**Comment by phkrief** [comment]
@ericpoirier could you add, next to both CfP buttons, a button to download "Proceeding Templates". Here is the file to link to this new button:
[templates.zip](https://github.com/EclipseFdn/events.eclipse.org/files/4682051/templates.zip)

With this last update, we should be all set. We might have to add a few more Technical Program Committee members. Nothing else, until the Revision 1.1 (targetted for June 8).
I will create a new bug for this revision.

Thx again for your great help

**Comment by phkrief** [comment]
Please forget my last request.
Susan suggests that we update the CfP instead.
So I will send you a new version of the CfP in few minutes

**Comment by phkrief** [comment]
Here is the new version of the CfP, so you don't need to change anything in the page but link the button to the new version of the file:
[Flyer-SAM IoT 2020 + Submission Guidelines Version 3.1.pdf](https://github.com/EclipseFdn/events.eclipse.org/files/4682439/Flyer-SAM.IoT.2020.%2B.Submission.Guidelines.Version.3.1.pdf)

**Comment by phkrief** [comment]
There is a new error in the following research department:

Prabhakaran Kasinathan, Siemens AG - **Corporate Technology, Cybersecurity Technology**

Can you fix it? Sorry about that. This error comes from this guy, btw ;-)
Thanks a lot

**Comment by phkrief** [comment]
I just noticed another (minor error) in the icon label: "Artificial Intelligencefor IoT" we should read instead "Artificial Intelligence for IoT".
Space is missing before "for".
Thx

**Comment by ericpoirier** [comment]
Hi Philippe,

I updated the staging page following the comments you made since yesterday.

https://deploy-preview-20--eclipsefdn-events.netlify.app/2020/sam-iot/

Please let me know if I missed anything.

Thanks.

**Comment by phkrief** [comment]
Thx @ericpoirier. You are almost done. You missed the following comments:
- https://github.com/EclipseFdn/events.eclipse.org/issues/19#issuecomment-634038861
- https://github.com/EclipseFdn/events.eclipse.org/issues/19#issuecomment-633718158

Thx a lot

**Comment by ericpoirier** [comment]
I made the updates you mentioned above.

https://deploy-preview-20--eclipsefdn-events.netlify.app/2020/sam-iot/

Let me know if there's anything else.

**Comment by phkrief** [comment]
+1

It looks good to me. Thx a lot for your work
