### ISSUE TITLE
Update to events.eclipse.org listing for Eclipse SAAM Mobility 

### ISSUE THREAD

**Issue by sjkiwai** [EclipseFdn/events.eclipse.org#195]
Hi there @autumnfound ,
Would you have a minute to update the description text?

Please remove: Submit your papers by April 16. 
Please replace with: Call for Posters, Demos and Work in Progress presentations closes May 28. 

![Screen Shot 2021-04-30 at 09 50 18](https://user-images.githubusercontent.com/7265777/116665312-ea3eb280-a999-11eb-8440-e6b4f295ea5e.png)

Thank you!
Susan

**Comment by autumnfound** [comment]
The best way to update this content is to email news@eclipse.org for edits since this is managed via the newsroom.

**Comment by sjkiwai** [comment]
OK Will send a mail to news@eclipse.org. Sorry for the confusion.
