### ISSUE TITLE
Working group site displaying past events

### ISSUE THREAD

**Issue by shanda-eclipse** [EclipseFdn/events.eclipse.org#202]
Some of our working group sites are showing past events on the homepage: https://openadx.eclipse.org/ or events in reverse order: https://edgenative.eclipse.org/. Is this a side-effect of this bug: https://github.com/EclipseFdn/events.eclipse.org/issues/6 or something intentional?

**Comment by chrisguindon** [comment]
This should be fixed now. The event div was missing a parameters for these 2 sites where we define if we should display past events or not.

**Comment by shanda-eclipse** [comment]
I checked all the working group sites and there are a few more with issues:
https://openmdm.org/
https://openmobility.eclipse.org/
https://openpass.eclipse.org/

**Comment by chrisguindon** [comment]
I pushed out some fixes to these sites! Should be good now!

Feel free to re-open if you find more issues!
