### ISSUE TITLE
CN4EF Day 2021 website

### ISSUE THREAD

**Issue by annejacko** [EclipseFdn/events.eclipse.org#215]
This is a virtual one-day event, co-located with and co-promoted by KubeCon NA 2021.

Event name: Cloud Native for Eclipse Foundation Day
Event date(s): TBD - either October 11 or October 12, 2021
Start time: TBD - probably 9am PT
End time: TBD - probably 5pm PT
Event Description: 
Cloud Native for Eclipse Foundation (CN4EF) Day is a full-day of expert talks, demos, and thought-provoking sessions focused on enterprise applications implemented using Eclipse Foundation projects on Kubernetes -- from the cloud and all the way to the edge. The Eclipse Cloud Development Tools, Jakarta EE, MicroProfile, and Eclipse Edge Native communities will all be represented.

***Note: the event is in October, but we need to know the URL of the event website by next Wednesday, July 28. I need to submit information to the Linux Foundation before I go on vacation.***

The briefing doc is here:
https://docs.google.com/document/d/1L3PX2XoOj5E5nKdYc-x7SHH2EYy1izzSPwjkaaehJJc/edit#

Thanks!

**Comment by chrisguindon** [comment]
The url format is:

https://events.eclipse.org/2021/[:pick-something-for-the-event]

**Comment by annejacko** [comment]
@croundy Clark, what URL should we use? Some possibilities:

https://events.eclipse.org/2021/cn4ef
https://events.eclipse.org/2021/cn4ef-day

**Comment by ericpoirier** [comment]
I started a PR and decided to go with the name https://events.eclipse.org/2021/cn4ef-day, but if you decide to choose another url, please let me know.

We can update this PR once we have more information about the event.

**Comment by croundy** [comment]
That works for now. Thanks!

**Comment by annejacko** [comment]
The URL looks good to me too.

Eric, what's the best way to move forward? I am thinking that we event organizers should look at websites for similar events we have done at the Foundation, and base the look on one of those. Then we can figure out what content will go where on the website, and establish a timeline for when we will have content ready for you to add.

Does that seems reasonable?

Some sites for us to look at would include these. They're somewhat similar, but I was assuming that we would go for this look, since it's simple and effective:
https://events.eclipse.org/2021/saam-mobility/
https://iot.eclipse.org/eclipse-virtual-iot-2021/
https://events.eclipse.org/2020/open-source-ai-workshop/
https://www.osdforum.org/

**Comment by ericpoirier** [comment]
> The URL looks good to me too.
> 
> Eric, what's the best way to move forward? I am thinking that we event organizers should look at websites for similar events we have done at the Foundation, and base the look on one of those. Then we can figure out what content will go where on the website, and establish a timeline for when we will have content ready for you to add.
> 
> Does that seems reasonable?

Yes I think that would be the right approche as we will be able to reuse layout elements that we've already built.

> Some sites for us to look at would include these. They're somewhat similar, but I was assuming that we would go for this look, since it's simple and effective:
> https://events.eclipse.org/2021/saam-mobility/
> https://iot.eclipse.org/eclipse-virtual-iot-2021/
> https://events.eclipse.org/2020/open-source-ai-workshop/
> https://www.osdforum.org/

**Comment by annejacko** [comment]
Noting here that we would like a new logo for the event website, so we will use the Creative Briefing doc to request that.

**Comment by chrisguindon** [comment]
@ericpoirier @annejacko,

The steps to move forward are already documented: 
https://github.com/EclipseFdn/events.eclipse.org#request-an-event-website



@annejacko We can start working on the website once your fill-up our required form.

**Comment by chrisguindon** [comment]
@annejacko When should we expect to work on this website?

**Comment by shanda-eclipse** [comment]
We have decided to use the EF logo on this webpage, rather than creating a new brand.

@annejacko I started a content doc so I could add in some details on how we will integrate the event brand:
https://docs.google.com/document/d/1oW4l-zRh0q12NL80tigIOHWLUDWmQN9LGpDInRH7bCQ/edit?usp=sharing

**Comment by annejacko** [comment]
@chrisguindon Hi Chris -- as mentioned in the first briefing doc, the goal is to have the website up for testing by September 3.

I'll continue to work on the website content doc that Shanda started. Please ping if we have failed to provide any info you need to get started, and we'll get you the necessary info / content. Thanks.

**Comment by chrisguindon** [comment]
Thanks @annejacko,

We will need the document to be completed by EOD Friday to meet that deadline. We ask for 2 weeks as we do have other priorities right + Eric is on vacation until mid-september.

**Comment by annejacko** [comment]
Ready to go for the initial version of the Website Content Doc:
https://docs.google.com/document/d/1oW4l-zRh0q12NL80tigIOHWLUDWmQN9LGpDInRH7bCQ/edit?usp=sharing

**Comment by annejacko** [comment]
@chrisguindon  That totally makes sense about needing a mockup if we go outside the template -- and about your team not spending time designing. :-) I will work with @meKokabi on that.

This wasn't obvious to me, even though I read the info in the briefing documents.

To close the loop on the menu, let's keep the standard menu. @shanda-eclipse had a good point about the site being hosted on eclipse.org so keeping it consistent is a good idea.

I would like to still do the soft launch on Monday if possible. We can leave off the WG section until we get the mockup. Also, since we don't have the info ready for the three buttons, could we add some text to the bottom of the Jumbotron where the buttons go, and say 
"Agenda and registration information is coming soon!"

I hope that by the time anyone looks at the page, we will have more to look at. Thanks!

**Comment by chrisguindon** [comment]
> @chrisguindon That totally makes sense about needing a mockup if we go outside the template -- and about your team not spending time designing. :-) I will work with @meKokabi on that. (This need for a mockup wasn't obvious to me, even though I read the info in the briefing documents.)

An alternative to a design would be to pointing us to something we already build in the past.  For example, you could say to us to copy the "Technical topics of interest" section from https://events.eclipse.org/2021/saam-mobility/

> To close the loop on the menu, let's keep the standard menu. @shanda-eclipse had a good point about the site being hosted on eclipse.org so keeping it consistent is a good idea.

+1

> I would like to still do the soft launch on Monday if possible. We can leave off the WG section until we get the mockup. Also, since we don't have the info ready for the three buttons, could we leave the buttons off for now, add some text to the bottom of the Jumbotron where the buttons go, and say
> "Agenda and registration information is coming soon!"


I will push an update soon. You can tell me if that's good enough for a soft launch and I will make it live.

**Comment by chrisguindon** [comment]
Links were removed and new text added:
https://deploy-preview-217--eclipsefdn-events.netlify.app/2021/cn4ef-day/

Let me know if you want me to push this live!

Thankjs

**Comment by annejacko** [comment]
@chrisguindon  Please make it live! Tnanks.

**Comment by chrisguindon** [comment]
Done! @annejacko, feel free to open a new issue whenever new changes are required! The page should be live any minute now!

**Comment by meKokabi** [comment]
Hello, please find the link below to the mockup page:
https://xd.adobe.com/view/0e18a6b2-4bb3-4beb-8373-99e9323c67ee-5b4b/
