### ISSUE TITLE
Please add Register button to CN4EF website

### ISSUE THREAD

**Issue by annejacko** [EclipseFdn/events.eclipse.org#218]
Hi -- please update the CN4EF website https://events.eclipse.org/2021/cn4ef-day/
to add the Register button in the Jumbotron. The button should go here: https://www.crowdcast.io/e/CN4EF

Since Monday is a holiday, would be great if this could be added tomorrow, Friday, Sept. 3.  Thanks!

**Comment by autumnfound** [comment]
@annejacko please see the following for a preview of the change https://deploy-preview-219--eclipsefdn-events.netlify.app/2021/cn4ef-day/

**Comment by annejacko** [comment]
@autumnfound Looks great! Please deploy. Thanks for the quick turnaround.
