### ISSUE TITLE
Code of Conduct for virtual events

### ISSUE THREAD

**Issue by sjkiwai** [EclipseFdn/events.eclipse.org#22]
We'd like to add a link to the Code of Conduct for virtual events to the SAM IoT webpage. Next release of the conference page is June 6th.

**Comment by chrisguindon** [comment]
@annejacko Should we create a generic Code of Conduct for all our events or will we create a page for each event?

**Comment by annejacko** [comment]
@chrisguindon I have drafted one and am waiting for Paul to review it. I will ping him again.

**Comment by annejacko** [comment]
@chrisguindon Paul has reviewed the updated Code of Conduct to be used for virtual events. Here is the Gdoc with the text: https://docs.google.com/document/d/1HpWqk2SjBgsCR89uWNV-7-3CyT8zf8LSYefL3lNJnh8/edit?ts=5ecc43a7

Every virtual event should reference this code somehow, but I'm not sure where it should be on each event's page / website. Seems like this is somewhat a design decision? @shanda-eclipse @ChristieWittEclipse

**Comment by chrisguindon** [comment]
> @chrisguindon Paul has reviewed the updated Code of Conduct to be used for virtual events. Here is the Gdoc with the text: https://docs.google.com/document/d/1HpWqk2SjBgsCR89uWNV-7-3CyT8zf8LSYefL3lNJnh8/edit?ts=5ecc43a7

Awesome!

> Every virtual event should reference this code somehow, but I'm not sure where it should be on each event's page / website. Seems like this is somewhat a design decision? @shanda-eclipse @ChristieWittEclipse

I was thinking of creating the page under https://events.eclipse.org/code-of-conduct/ but like you, it's not clear to me where we should include a link to this page.

@annejacko Should this link be on every event page by default?

**Comment by ChristieWittEclipse** [comment]
@chrisguindon @annejacko I just reviewed other virtual event websites, and it seems like they're placing the "Code of Conduct" in the top menu. So in that case, I would suggest placing it on the right side of "Projects" in the screenshot below.
![Screen Shot 2020-05-26 at 11 34 13 AM](https://user-images.githubusercontent.com/58480647/82920209-0396dd80-9f45-11ea-94d9-a8b4a443da6d.png)

@shanda-eclipse can you +1 if you agree?

**Comment by chrisguindon** [comment]
I would prefer an option where we don't modify the eclipse.org menu unless we replace it completely.

@ChristieWittEclipse  Could this be something we add in the jumbotron?

**Comment by ChristieWittEclipse** [comment]
+1, I don't think it should go in the Jumbrotron because its not a main CTA. It could be placed as a hyperlink, below the "About the Event" section. Maybe every event description should end with a sentence like "View our event code of conduct."

**Comment by annejacko** [comment]
It seems like the only element each event will have is the "About the Event" section... correct? Personally, I don't like the idea of referencing it at the end of every event description as text that is part of the description. Could we perhaps have a smalllish orange button, centered, below the "About the Event" text, that says "Code of Conduct" or "Community Code of Conduct"?

**Comment by ChristieWittEclipse** [comment]
@annejacko I like that idea as well!

**Comment by shanda-eclipse** [comment]
> Could we perhaps have a smalllish orange button, centered, below the "About the Event" text, that says "Code of Conduct" or "Community Code of Conduct"?
I look at look at the template and think this is our best option.

**Comment by chrisguindon** [comment]
+1 I like the idea of adding a link to the CoC in the "Registration/About the Event" section.

**Comment by annejacko** [comment]
@chrisguindon Just a note that I updated the CoC to change the headline. https://docs.google.com/document/d/1HpWqk2SjBgsCR89uWNV-7-3CyT8zf8LSYefL3lNJnh8/edit?ts=5ec317fb#heading=h.gf7vhy47a6bt

**Comment by chrisguindon** [comment]
In an effort to get the ball rolling, I created the first draft:
https://deploy-preview-27--eclipsefdn-events.netlify.app/code-of-conduct/

Now, we just need to figure out how we are going to link to this page.

**Comment by ChristieWittEclipse** [comment]
+1 to have a small orange button, centered, below the "About the Event" text, that says "Community Code of Conduct".

**Comment by annejacko** [comment]
I like Christie' suggestion for the placement of the CoC link.

**Comment by chrisguindon** [comment]
How about this:
https://deploy-preview-27--eclipsefdn-events.netlify.app/2020/sam-iot/

**Comment by chrisguindon** [comment]
I did not see your comment about naming the link "Community Code of Conduct" before pushing my change.

I am thinking of using  Code of Conduct" since it smaller? What do you all think?

**Comment by ChristieWittEclipse** [comment]
+1, I like the shorter version "Code of Conduct".

**Comment by annejacko** [comment]
I think it looks good with the shorter label, and I like the placement.
