### ISSUE TITLE
Update to CN4EF Day website

### ISSUE THREAD

**Issue by annejacko** [EclipseFdn/events.eclipse.org#220]
Since @chrisguindon suggested opening new issues with update requests, here goes.

We have new content to add to this site: https://events.eclipse.org/2021/cn4ef-day

Here is the mockup that @meKokabi did for the WG section:
https://xd.adobe.com/view/0e18a6b2-4bb3-4beb-8373-99e9323c67ee-5b4b/

The text and links to the logos are in this website content doc:
https://docs.google.com/document/d/1oW4l-zRh0q12NL80tigIOHWLUDWmQN9LGpDInRH7bCQ/edit#

Thanks!

**Comment by chrisguindon** [comment]
This is great @annejacko and @meKokabi!

When is this needed? 

Should we expect the content for the agenda/speaker to be provided before we push this update live or will want to remove those section for the next revision?

**Comment by annejacko** [comment]
@chrisguindon  It's going to take a bit of time for the agenda and speakers, so for now, we can't include those sections as shown in the mockup. But it would be great to have the WG info added soon. We will start promoting next week, so the more content by then, the better. Thanks.

**Comment by ericpoirier** [comment]
Hi @annejacko and @meKokabi,

Where can I find the background image that is used in this mockup?

Thanks.

**Comment by meKokabi** [comment]
Hi Eric,
All the assets have been added here:
https://github.com/EclipseFdn/events.eclipse.org/issues/215
Let me know if you want me to re-add it .
Best,
M

**Comment by chrisguindon** [comment]
@annejacko,

We don't typically change the look and feel of the featured footer. The orange section in @meKokabi. We would prefer to keep this consistent since these are shown across all our websites.

Are you ok with us keeping that section as-is?
https://deploy-preview-221--eclipsefdn-events.netlify.app/2021/cn4ef-day/

**Comment by meKokabi** [comment]
Looks good to me!

**Comment by linkfang** [comment]
> @annejacko,
> 
> We don't typically change the look and feel of the featured footer. The orange section in @meKokabi. We would prefer to keep this consistent since these are shown across all pages.
> 
> Are you ok with us keeping that section as-is?
> https://deploy-preview-221--eclipsefdn-events.netlify.app/2021/cn4ef-day/

Besides, as we don't have the agenda and speakers, so I keep the sentence "Agenda information is coming soon!" in the jumbotron. Please let me know if you would like to remove it. Thanks!

**Comment by annejacko** [comment]
The preview looks good to me! Thanks.
