### ISSUE TITLE
Logos' sizing adjustment on CN4EP Day webpage

### ISSUE THREAD

**Issue by meKokabi** [EclipseFdn/events.eclipse.org#223]
Hello, Please re-adjust the banner's logos: 
The 4 logos including Jakarta, MicroProfile, Edge Native, and Cloud Dev Tools need to have same sizing. Currently Jakarta is too small and Edge Native too large. Please make them all consistent . Let me know if you think it might be easier to adjust with pngs.
Thanks,
Mehrnaz

Page link : https://events.eclipse.org/2021/cn4ef-day/
[Logo-svg& png.zip](https://github.com/EclipseFdn/events.eclipse.org/files/7163946/Logo-svg.png.zip)

**Comment by linkfang** [comment]
Hi @meKokabi ,
Please preview the changes here:
https://deploy-preview-224--eclipsefdn-events.netlify.app/2021/cn4ef-day/

**Comment by meKokabi** [comment]
It looks good to me, thanks!
