### ISSUE TITLE
Add Agenda / Session info to CN4EF Day website

### ISSUE THREAD

**Issue by annejacko** [EclipseFdn/events.eclipse.org#226]
We have the data for the agenda now for CN4EF Day.
https://events.eclipse.org/2021/cn4ef-day/ 

It's in this document:
https://docs.google.com/document/d/1oW4l-zRh0q12NL80tigIOHWLUDWmQN9LGpDInRH7bCQ/edit#heading=h.7nkf5tunp8zb

Can you please go ahead and add this now, and not wait for the speaker details? That will be coming next, but we want to start more heavily promoting the agenda without waiting for the rest of the speaker data. Thanks.

Let me know if I missed anything!

FYI @croundy

**Comment by ericpoirier** [comment]
> We have the data for the agenda now for CN4EF Day.
> https://events.eclipse.org/2021/cn4ef-day/
> 
> It's in this document:
> https://docs.google.com/document/d/1oW4l-zRh0q12NL80tigIOHWLUDWmQN9LGpDInRH7bCQ/edit#heading=h.7nkf5tunp8zb
> 
> Can you please go ahead and add this now, and not wait for the speaker details? That will be coming next, but we want to start more heavily promoting the agenda without waiting for the rest of the speaker data. Thanks.
> 
> Let me know if I missed anything!
> 
> FYI @croundy

By leaving the speaker details out, do you mean that we wait to create the speakers page and don't add the link in the agenda?
Example: https://events.eclipse.org/2021/saam-mobility/speakers/#andreas_riexinger

**Comment by annejacko** [comment]
Hi Eric -- Yes, I need to wait to create the Speakers page since I don't have all the info. But we are late with getting the agenda up, so we would like to add it ASAP.,

This also means updating the text in the header that currently says "Agenda information is coming soon!" to a button that goes to the Agenda.

Question: I have included the speaker's job title and company along with their name in the Agenda data. If that can fit into the name field nicely, let's keep it. But if it's better to just use the name, we can eliminate that since the same info can be in the bio.

**Comment by annejacko** [comment]
Eric, I have an update. I just managed to get a bunch of speaker data, so I think we can add the Speakers page now (or at least an hours from now). So let's wait, and I'll update this issue when I have the Speaker data ready!

**Comment by ericpoirier** [comment]
> Eric, I have an update. I just managed to get a bunch of speaker data, so I think we can add the Speakers page now (or at least an hours from now). So let's wait, and I'll update this issue when I have the Speaker data ready!

Ok sounds good, thanks for the update.

@linkfang, you can start working on this issue with you have the chance, create a draft PR and add the remaining speaker data when Anne provides them.

**Comment by annejacko** [comment]
Hi - I now have the data for the Speakers. It's in this file:
https://docs.google.com/document/d/1oW4l-zRh0q12NL80tigIOHWLUDWmQN9LGpDInRH7bCQ/edit#heading=h.htp0nqerwzfd

Attaching the Zip folder with the speaker photos.

So we can now have two new buttons in the header: Agenda and Speakers

Thanks
[CN4EF_Day_speaker_photos.zip](https://github.com/EclipseFdn/events.eclipse.org/files/7187185/CN4EF_Day_speaker_photos.zip)
s.

**Comment by linkfang** [comment]
Hi @annejacko ,

Please preview the changes here:
https://deploy-preview-227--eclipsefdn-events.netlify.app/2021/cn4ef-day/

**Comment by annejacko** [comment]
Thanks -- it looks really good! Just a couple of items.

- In the Jumbotron, please remove the text "Agenda information is coming soon"
- In the Jumbotron, include three orange buttons that link to the appropriate page or section:  1)Registration   2) Agenda  3)Speakers.  (In other words, change the text of the "Event Registration" button to just say "Registration," and add the other two orange buttons.)
- Since we don't have a keynote, could we changed the color that indicates a Panel in the agenda to use orange instead of dark gray? Color  #f79623

**Comment by linkfang** [comment]
No problem!

Please preview the updated version here:
https://deploy-preview-227--eclipsefdn-events.netlify.app/2021/cn4ef-day/

**Comment by annejacko** [comment]
It's great! Please make it live. I'll be sharing it with the speakers so they can check all their data. Thanks so much.
