### ISSUE TITLE
Change Speaker Oreder on CN4EF Day

### ISSUE THREAD

**Issue by brianking** [EclipseFdn/events.eclipse.org#228]
RE:
https://events.eclipse.org/2021/cn4ef-day/

In the Speakers section, I propose we move one or both of the women speakers to the first page of the carousel, to reflect/promote diversity at the event.

**Comment by ericpoirier** [comment]
Hi @brianking, can you tell us which speakers you'd like to add to the first page and where in the list?

Thanks.

**Comment by linkfang** [comment]
Hi @brianking ,
How is the order on this preview page:
https://deploy-preview-229--eclipsefdn-events.netlify.app/2021/cn4ef-day/

**Comment by brianking** [comment]
Looks good, only other change I would make is to replace me on the first page Kilton Hopkins.

**Comment by linkfang** [comment]
Cool, here is the new change:
https://deploy-preview-229--eclipsefdn-events.netlify.app/2021/cn4ef-day/

**Comment by ericpoirier** [comment]
@brianking can you give us the +1 to go live with these changes?

Thanks.

**Comment by brianking** [comment]
+1 Thank you!
