### ISSUE TITLE
Newsletter sign up or upcoming events on virtual event template

### ISSUE THREAD

**Issue by sjkiwai** [EclipseFdn/events.eclipse.org#23]
Is it possible to choose between the upcoming events or Foundation Newsletter sign up on the virtual events template? 

For SAM IoT, if we need to show the Foundation Newsletter, could we show somehow that it is the Foundation newsletter (rather than the SAM IoT newsletter). 

Thank you!
Susan

**Comment by shanda-eclipse** [comment]
Ideally events.eclipse.org and all subpages would use the same footers as eclipse.org, so we can highlight the most timely/relevant information and ensure out key CTA's are getting the most views. However, this may be a secondary step. If we are looking for a single CTA that remains on all event pages, I would suggest upcoming events.

**Comment by chrisguindon** [comment]
I agree with Shanda.  The featured footer is something that the marketing team owns. 

@sjkiwai With that said, there is nothing stopping us from adding a new section before the featured story to promote something important about that event!
