### ISSUE TITLE
Update content for SAMIoT 2020 Conference (Revision 1.1)-Target June 8

### ISSUE THREAD

**Issue by phkrief** [EclipseFdn/events.eclipse.org#24]
For this revision, we would to update the website as follow:

- Link to registration (June 8) - in Location section (@susan will provide the link)
- Add CFP and Submission Guidelines as hugo pages (@phkrief will provide the expected layout)
- TPC updates (more people) - A complete list should be available June 2
- Add link to Code of Conduct  - @annejacko will provide the link.

Thanks a lot

**Comment by annejacko** [comment]
FYI Code of Conduct is ready; I updated this issue on the topic: https://github.com/EclipseFdn/events.eclipse.org/issues/22

**Comment by phkrief** [comment]
@ericpoirier You should have all the inputs to update the website for its Revision 1.1

Thx a lot

**Comment by phkrief** [comment]
We have a new TPC member:

> - Alessio Angius, ISI Foundation
> - Luca Anselma, University of Turin
> - Paolo Azzoni, Eurotech
> - Peter Bednár, Technická univerzita v Košiciach
> - Ilaria Bosi, LINKS Foundation
> - Paolo Brizzi, Competence Center Industry Manufacturing 4.0
> - Benoit Combemale, University of Toulouse INRIA
> - Davide Conzon, LINKS Foundation
> - João Pedro Correia dos Reis, Faculty of Engineering, University of Porto - FEUP
> - Maria Teresa Delgado, Eclipse Foundation
> - Frederic Desbiens, Eclipse Foundation
> - Charalampos Doukas, Amazon Web Services
> - Juliver Gil, Universidad de Antioquia
> - Laurent Gomez, SAP Security Research
> - Gil Gonçalves, Faculty of Engineering, University of Porto - FEUP
> - Marco Jahn, Eclipse Foundation
> - Prabhakaran Kasinathan, Siemens AG - Cybersecurity Technologies
> - Zakaria Laaroussi, Ericsson Finland
> - Cesar Marin, Information Catalyst for Enterprise - ICE
> - Yod Samuel Martín, Universidad Politécnica de Madrid
> - Claudio Pastrone, LINKS Foundation
> - Ivana Podnar Žarko, University of Zagreb, Faculty of Electrical Engineering and Computing
> - Mohammad Rifat Ahmmad Rashid, University of Liberal Arts Bangladesh – ULAB
> - Alejandra Ruiz Lopez, Tecnalia
> - Julian Schütte, Fraunhofer AISEC
> - Tomáš Sabol, Technická univerzita v Košiciach
> - Xu Tao, LINKS Foundation
> - Massimo Vecchio, Università degli Studi eCampus
> - Mark Vinkovits, Pasero

@chrisguindon @ericpoirier can we still plan June 8th? 
The only missing thing I'm aware of is the CoC. @annejacko any update on that? Thx a lot

**Comment by chrisguindon** [comment]
@phkrief I posted the CoC yesterday:
https://events.eclipse.org/2020/sam-iot/

**Comment by autumnfound** [comment]
I've taken on the updates for the event. I've requested access to the google docs attached. The only other thing I need is some context around what "TPC" is

**Comment by phkrief** [comment]
Hi @autumnfound 
the TPC is the Technical Program Committee. 
The TPC section of https://events.eclipse.org/2020/sam-iot/ has to be updated with the list provided in the comment https://github.com/EclipseFdn/events.eclipse.org/issues/24#issuecomment-638829086.

HTH

**Comment by phkrief** [comment]
Quick question: I thought that the process in place was supposed to wait for a "+1" before publishing. Why is it different in this case?
Thanks

**Comment by chrisguindon** [comment]
@phkrief This is definitely needed for the initial website since I want the owner to sign-off on the website we are delivering.

I don't always require it for a revision since those are often time-sensitive. If I see something that we might not be sure, I will definitely ask for a +1.

I try to use my judgement to allow us to be efficient. If you prefer to always +1 a change, we can do that moving forward for projects that you are involved!

**Comment by phkrief** [comment]
@chrisguindon this is fine with me. I was just surprised to see the website updated w/o any request from your side to approve knowing, yes, the changes were minor on the main page but the second page was completely new.

In any case thanks fo @autumnfound for his great job to deliver it on time.

Kind regards
