### ISSUE TITLE
Update to Open Source AI Workshop to add final speaker

### ISSUE THREAD

**Issue by annejacko** [EclipseFdn/events.eclipse.org#34]
Hi,
We have our missing speaker! Please update the website to add him to the speaker session and to the agenda section.
https://events.eclipse.org/2020/open-source-ai-workshop/
Speaker photo attached.

Text for under his photo:
Barry O’Sullivan
President (AI4EU - European AI Association); Professor (University College Cork, Ireland)

Text for Agenda - he is giving the talk at 9:45 that currently is missing a Presenter Name.
Barry O'Sullivan

Thanks!
![barry-osullivan](https://user-images.githubusercontent.com/29178654/83901845-42305300-a710-11ea-89ae-d2019b0ba46b.jpg)

**Comment by chrisguindon** [comment]
@annejacko You can review the changes here:
https://deploy-preview-35--eclipsefdn-events.netlify.app/2020/sam-iot/
