### ISSUE TITLE
Please create a "Save the Date" website for JakartaOne Livestream

### ISSUE THREAD

**Issue by annejacko** [EclipseFdn/events.eclipse.org#36]
We are doing another JakartaOne Livestream event in September 2020, similar to the one we did in September 2019. So it's time to get the Save the Date website up. We will be adding items as they become available.

The plan is to have this up next week (week of June 8), but I got distracted and forgot to ask for it. Oops.

Here is the link to the event website request form:
https://docs.google.com/document/d/1vhryrKbF3ZlLQ73g-hb7vBizZJckcMD1/edit

Since I find it a bit hard to see the additions to the document, I tried to put all my content in bold red so you can see where it is.

Attaching
[JakartaOne Livestream logos.zip](https://github.com/EclipseFdn/events.eclipse.org/files/4738503/JakartaOne.Livestream.logos.zip)
 a zip file with the JakartaOne Livestream logos. I believe they are the same as the ones you have previously used, so you could just use those.

Note that I don't have access to the header image, but it's the same one you have used before.

**Comment by annejacko** [comment]
I have the header image file too! Attaching.
![home-background](https://user-images.githubusercontent.com/29178654/83927846-ff3ba300-a742-11ea-8ff4-81a28782a25e.jpg)

**Comment by autumnfound** [comment]
Closing, as a new issue has been created in the JakartaOne repository: jakartaee/jakartaone.org#127
