### ISSUE TITLE
Update Open Source AI Workshop website now that event is over

### ISSUE THREAD

**Issue by annejacko** [EclipseFdn/events.eclipse.org#42]
Hi -- Now that the event is over, we need to update it to remove the "Register" button in the header.

We could perhaps wait to see when the YouTube recordings will be available, since the site will nee to be updated to add that info too.

I'm not sure we have discussed this, but maybe for a site like this, the "Register" button could be changed to a button that says something like "Watch Recorded Talks" and links to the YouTube page?

@gaelblondelle @Ioana240 WDYT?

**Comment by Ioana240** [comment]
@annejacko @gaelblondelle That's a great idea, Anne. We can replace the "Register" button with a "Watch recorded Talk" button with links to YouTube once we have the single video sessions ready to be published.
@gaelblondelle I will have a chat today with Christie about editing these videos, and will keep you posted on how/when/whether Christie could edit the videos among her other tasks and timelines.

Thank you!
-Ioana

**Comment by annejacko** [comment]
@Ioana240 Thanks. Just let me know more about the recordings when you have that info!

**Comment by Ioana240** [comment]
@annejacko Sure! I will let you know as soon as we have the single video sessions ready.
I discussed with Christie and we decided we could have the videos ready by July 1. I keep you posted if there are additional details or changes on the timeline

**Comment by autumnfound** [comment]
This is live
