### ISSUE TITLE
Create a new website for the #2 Eclipse AI Workshop

### ISSUE THREAD

**Issue by gaelblondelle** [EclipseFdn/events.eclipse.org#52]
Hi team,

We will have a new AI Workshop on September 10th. 
The https://events.eclipse.org/2020/open-source-ai-workshop/ website was perfect for what we want to do. 
So I would like to duplicate it for this second workshop (spoiler: we may run a 3rd workshop by the end of the year :) ).

Then, I would like to try to update the website myself through a pull request to see how I can lower the burden on your side. 

Cheers,
Gaël

**Comment by chrisguindon** [comment]
I am assigning this back to you,  now that the initial PR is created!

Please reach out if you run into any problem!

**Comment by chrisguindon** [comment]
Closing this bug since this new event is live!
