### ISSUE TITLE
Display past events

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/events.eclipse.org#6]
Starting May 1st, we will need to fetch events from https://newsroom.eclipse.org/api/events

This new API will only return 100 events at the time. We will need to paginate the result to fetch all events!

**Comment by chrisguindon** [comment]
We are now pulling the last 100 events. 

This works but it would be nice to view past events.

**Comment by chrisguindon** [comment]
This feature is planed has phase 2 of https://github.com/EclipseFdn/events.eclipse.org/issues/15

**Comment by flora8984461** [comment]
@shanda-eclipse Hi Shanda, please check the preview: https://deploy-preview-111--eclipsefdn-events.netlify.app/ . 
Except for the scroll tool bar on the event "Web-based tools - built with Eclipse (only) - Cloud Tool Time (Maximilian Koegel)...", other functions should be ready.

The search textbox will start fetching data when you type 3 characters or above (to be less often hitting the server).

Past events show when the checkbox "show past events" is ticked.

Please feel free to let me know if you have any feedback. Thanks!

**Comment by shanda-eclipse** [comment]
Event type = unknown is a weird filter to include. In fact, we should look at how the event type filters are used, as it seems like they aren't mutually exclusive categories (should probably be a separate bug)

Regardless of how many events are displaying, you have to click "Load more" to see the past events. This doesn't seem super user friendly. Ex. filtered to "Other interesting events" so only one upcoming event would show. I still had to click "Load more" to see past events.

**Comment by chrisguindon** [comment]
> Event type = unknown is a weird filter to include. In fact, we should look at how the event type filters are used, as it seems like they aren't mutually exclusive categories (should probably be a separate bug)

This is there for legacy reasons. The previous website had events to a type "unknown".  I am assuming that someone in the Marketing team made an update in the newsroom to change to update those events since that filter no longer returns any results.

We can remove it from the list if this is no longer needed. Otherwise, @autumnfound suggested that we renamed this to uncategorized.


> Regardless of how many events are displaying, you have to click "Load more" to see the past events. This doesn't seem super user friendly. Ex. filtered to "Other interesting events" so only one upcoming event would show. I still had to click "Load more" to see past events.

I  agree that this still needs some work on our end.

I think we should remove the option for viewing past events. I don't think we need an option to show past events. If the user is still scrolling after the upcoming events, we should make it easy for them to view past events.

This is what I am thinking:

Let's assume that our default is to show 10 new event at a time.

Let says that the user clicks on the "Training series" filter. The site should try to fetch 10 upcoming events. Now that might not always be possible, we might only have 1 upcoming event.

If that the case, my expectation would be to show 1 upcoming event and 9 past events.

@shanda-eclipse , @flora8984461 ,

WDYT?

**Comment by shanda-eclipse** [comment]
Let's remove "Unknown" since it isn't being used.

Past events recommendation makes sense, but I'd like to see how it works once implemented.

**Comment by chrisguindon** [comment]
@linkfang A pr was already started for this issue but it's not finished:
https://github.com/EclipseFdn/events.eclipse.org/pull/111

Can you take some time to review the current work that is being done as you will be asked to finish this.

I think the last remaining feature is the following:

> It does seem strange that when scrolling through the list, it moves directly from upcoming events to past events without any sort of indication.

A Netlify preview is available here:
https://deploy-preview-111--eclipsefdn-events.netlify.app/

**Comment by shanda-eclipse** [comment]
I think @linkfang had it correct that once the end time of the event has passed, it becomes a past event. 

However, I am noticing that only 8 upcoming events are displaying, when there are more than that on the list.

**Comment by shanda-eclipse** [comment]
> That's because today's events are moved to past events, making it look like only 8 upcoming ones available, but if you click on load more, you will see more upcoming events in the list.

I would expect to see all upcoming events before past events (ex. EclipseCon 2021 is the furthest out upcoming event). So I see two options:
1. Display ALL upcoming events and 2 past events with the "Load More" button to show the past events.
OR
2. Display 8 upcoming events, then the "Load More" button that loads more upcoming events. Followed by 2 past events, and a "Load more" button that loads more past events.

**Comment by linkfang** [comment]
Hi @shanda-eclipse , please preview the changes here:
https://deploy-preview-199--eclipsefdn-events.netlify.app/

**Comment by shanda-eclipse** [comment]
+1 to go live

**Comment by shanda-eclipse** [comment]
Sorry, just found another issue. EclipseCon 2021 is on the list twice. I'm assuming the staging site uses the live CMS, so I'm looking at the newsroom to see what's going on.

**Comment by shanda-eclipse** [comment]
Fixing the data in the CMS fixed the display. So we are good to go live.

Official +1

**Comment by chrisguindon** [comment]
It's a wrap! Thanks @linkfang and @flora8984461 :)
