### ISSUE TITLE
EclipseCon 2020

### ISSUE THREAD

**Issue by vgriffiths** [EclipseFdn/events.eclipse.org#7]
Event Name: EclipseCon
Type of event: ec
Date: October 19 - 22, 2020
Registration URL: 
Website URL: https://www.eclipsecon.org/2020
Location name: Virtual
Street: 
Zip/Postal code:
City:
Country: 
Latitude:
Longitude:

### Type of event
It can be any of the following:

* dc - Demo Camp & Stammtisch
* wg - Working Group Events
* ec - EclipseCon
* ed - Eclipse Day & Hackathons
* et - Training Series
* ee - Other interesting Events
* ve - Virtual Events

**Comment by chrisguindon** [comment]
@autumnfound can you take a look to see why EclipseCon is not showing in the list of events?

**Comment by chrisguindon** [comment]
i made an update to this site and now events are being pulled from newsroom.eclipse.org.
