### ISSUE TITLE
MQTT Sparkplug webinar - September 23, 2020

### ISSUE THREAD

**Issue by fdesbiens** [EclipseFdn/events.eclipse.org#75]
Hi.

The Sparkplug working group is requesting an event page for a webinar taking place on September 23, 2020. 

The content template is here: https://docs.google.com/document/d/1vR6UOv5z0Ngzzi-OXYuctkmjskp-A8razvwk5MPlN1w

I have the photos for the speakers but need to tweak them to your specifications. Should I attach them to this issue once ready?

Please note we do not need an agenda section on the page. 

This request is time sensitive. Let me know what I can do to assist your team in order to reduce lead time.

**Comment by autumnfound** [comment]
Hi Frederic, It looks like its mostly in order! My only question is that you have a speaker under a Host category in your document. Is this person to be displayed in a different way, or is that just for internal documentation? For the pictures, as soon as you're ready to, feel free to zip them and attach them here!

**Comment by fdesbiens** [comment]
@autumnfound Thank you for your quick reply! They would like to have the host displayed in a special way. Whatever you can do easily will do. I will upload the pictures soon.

**Comment by autumnfound** [comment]
We could add a separate speaker section for the host, or we could add `Host` to his entry so that it displays as part of his name. So it would be like the following:
```
+-------------------+
|                   |
|      image        |
|                   |
+-------------------+
<Speakers name>, Host
   <Speaker title>
```

**Comment by fdesbiens** [comment]
@autumnfound That works for me. Attached are the speaker pictures I was provided.
[SparkplugWebinarSpeakers.zip](https://github.com/EclipseFdn/events.eclipse.org/files/5150944/SparkplugWebinarSpeakers.zip)

**Comment by autumnfound** [comment]
Preview available of 1st draft: https://deploy-preview-76--eclipsefdn-events.netlify.app/2020/mqtt-sparkplug/

**Comment by Ioana240** [comment]
Hi Martin,

We have a few changed on the current preview:

1. Could you please change the title from: "Keep Your IIoT Projects From Failing.
WEBINAR: Learn How MQTT Sparkplug Makes IIoT Easy" to **"Webinar: The 80’s Called and They Want Their Architectures Back: how MQTT actually converges IT & OT for faster systems integration"**

2. In the "Speakers Section", the speaker photos are placed more to the left, could you please align them more in the center of the page so that it looks consistent with the rest of page structure?

3. For the 2 "REGISTER NOW" CTA buttons, could you please use this link: https://www.crowdcast.io/e/sparkplug_wgce_sept23_20 and delete the links that are currently linked to both CTA buttons?

Thank you!
Ioana

**Comment by autumnfound** [comment]
1. The text you reference is 2 fields, and that is an awful lot of text to put into either of them. How would you want to cut that text into 2 fields?
2. I can look into that!
3. Can do

**Comment by Ioana240** [comment]
1. Sounds good, let's cut the title text into 2 fields

"Webinar-  The 80’s Called and They Want Their Architectures Back:

How MQTT Actually Converges IT & OT for Faster Systems Integration"

Thank you!!

**Comment by autumnfound** [comment]
This has been updated @Ioana240 @fdesbiens, how does it look in the preview?

**Comment by fdesbiens** [comment]
@autumnfound Things are looking good! Personally I would make the speaker portraits a tad smaller but I will defer to you and @Ioana240 about this.

**Comment by Ioana240** [comment]
@autumnfound @fdesbiens It looks good! I would also adjust a bit the size of the speaker photos. Apart from that, we could go live with this webpage 

Thank you, Martin!

**Comment by autumnfound** [comment]
We don't currently have a fine enough control needed to make them both centered and smaller in the framework. This is about as good as I could get it with the current state

**Comment by autumnfound** [comment]
This has now been merged in! It should be live soon.

**Comment by autumnfound** [comment]
@Ioana240 for new events to be present on eclipse.org, they need to be added to the newsroom site which manage our events. Its expected that people that request events would create the entry on the site through https://newsroom.eclipse.org/node/add/events

**Comment by Ioana240** [comment]
@autumnfound When I add an event in the Newsroom, I also have to add a link to the respective event. which link should I use for the Sparklug community event. I only have the preview from this bug. is this the final link or is there another link I can add in the Newsroom?

**Comment by autumnfound** [comment]
https://events.eclipse.org/2020/mqtt-sparkplug/ is the live link

**Comment by Ioana240** [comment]
@autumnfound Awesome! Thank you Martin!!
