### ISSUE TITLE
Add JakartaOne Livestream to the Eclipse Events webpage

### ISSUE THREAD

**Issue by GraehamHui** [EclipseFdn/events.eclipse.org#8]
## Event Information

Event Name: JakartaOne Livestream Cloud Native for Java
Type of event: ve
Date: May 12, 2020
Registration URL: https://www.crowdcast.io/e/80qdj1bq
Website URL: https://jakartaone.org/cn4j2020/

**Comment by chrisguindon** [comment]
Hi @GraehamHui,

We are now live to manage events via newsroom.eclipse.org. Can you try to submit this event via https://newsroom.eclipse.org/node/add/events

**Comment by chrisguindon** [comment]
This was done buy @GraehamHui
