### ISSUE TITLE
What coming up next week

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/events.eclipse.org#95]
Posted by @annejacko via https://github.com/EclipseFdn/events.eclipse.org/issues/15#issuecomment-696157753

Adding feedback on the new page as viewed here: https://deploy-preview-87--eclipsefdn-events.netlify.app/

Looks good.. the one thing that I miss is a list of all upcoming events by date. I realize the squares featuring the various events are ordered by date, but that's not obvious. If someone wanted to know "what coming up next week" they would have to look a bit. Maybe a list by date on the left side?

**Comment by chrisguindon** [comment]
Perhaps we could add a filter or a button that would allow folks to only see events for the upcoming week?

**Comment by flora8984461** [comment]
@chrisguindon Is this still a requirement? Since if I'm going to implement this, it would be somehow incompatible with https://github.com/EclipseFdn/events.eclipse.org/pull/111,  because there I directly call the APIs when doing the filters. Unless we have an API for "upcoming weeks". 🤔

**Comment by chrisguindon** [comment]
You should be able to calculate which events are starting within 7 days of the current time?

**Comment by flora8984461** [comment]
Note: Let's make this after https://github.com/EclipseFdn/events.eclipse.org/pull/111 is done.

**Comment by chrisguindon** [comment]
WONT FIX.
