### ISSUE TITLE
Add missing bg for event types

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/events.eclipse.org#96]
As described by @flora8984461 via https://github.com/EclipseFdn/events.eclipse.org/issues/15#issuecomment-696845583

Currently, we have event types:

EclipseCon
Virtual Event
Demo Camps & Stammtisch
Working Group Events
Training Series
Other interesting Events
Unknown
But from the XD design (https://xd.adobe.com/view/dbc61752-c869-4bab-525b-de389b574b56-adf7/), I only have three background images for event card.

According to @chrisguindon , we want to use different background images for each type of events.

For now, I temporarily replace other types of events using default black background.

Would you mind providing me for each event type, what background image would you like to use?

The screenshot shows how I organize the images with event types so far.

![93912652-024aa700-fcd2-11ea-8cad-79b162ab0f54](https://user-images.githubusercontent.com/893942/94042135-2e7d2b00-fd99-11ea-9fdd-131b1ad36c79.png)

**Comment by jph152** [comment]
![Demo Camps   Stammtisch BG](https://user-images.githubusercontent.com/69642121/94049511-16aaa480-fda3-11ea-9bf6-105f0df7b450.png)
![EclipseCon BG](https://user-images.githubusercontent.com/69642121/94049515-18746800-fda3-11ea-925a-6892715f85b8.png)
![Training Series BG](https://user-images.githubusercontent.com/69642121/94049523-1ad6c200-fda3-11ea-86ee-c39765d1e04b.png)

**Comment by flora8984461** [comment]
@jph152  thanks! updated the images. 
Just FYI: unknown type is still using the pure black image I created.

**Comment by chrisguindon** [comment]
I think we are fine with the pure black images.
Thanks @jph152 for sending these images our way!
