### ISSUE TITLE
Add a legend to the main page of events.eclipse.org

### ISSUE THREAD

**Issue by hudsonkelly83** [EclipseFdn/events.eclipse.org#98]
Add a legend to the main page of events.eclipse,org at the next update that identifies what the colors behind each event mean. 

![image](https://user-images.githubusercontent.com/70344546/94054215-5d030200-fda9-11ea-982e-eb71a36d6d82.png)

ie: Brown = Eclipse Events, Black = other interesting event, Blue = working group event

I'll leave it to you guys how you want to make it look, but just an idea.

**Comment by chrisguindon** [comment]
Resources from Matt:

I updated this XD link to a Development link with downloadable assets: https://xd.adobe.com/view/dbc61752-c869-4bab-525b-de389b574b56-adf7/

I am also including a local XD file if needed here: https://drive.google.com/drive/folders/1G6mQzGAJEMuW-Liiu4Z8DifU0IKGCjWM?usp=sharing

For the look, we can implement the design that was created by Matt!

![Screen Shot 2020-09-23 at 2 38 27 PM](https://user-images.githubusercontent.com/893942/94055084-76587e00-fdaa-11ea-8dc7-1a0d3c77cd7f.png)

**Comment by hudsonkelly83** [comment]
Thabang has also requested a few more edits next time you update. 

1: Alphabetize the 'CATEGORIES' section: 
![image](https://user-images.githubusercontent.com/70344546/94059372-4f04af80-fdb0-11ea-9586-5ada29f6d8ca.png)

ie: Eclipse IDE should be much higher, Tangle EE at the bottom

2: Under 'EVENT TYPES' add an 's' onto Virtual Event to make it 'Virtual Events' (to standardize it with the other two being plural) 
![image](https://user-images.githubusercontent.com/70344546/94059579-a3a82a80-fdb0-11ea-8bec-82d1715349dd.png)
